gateway:
  port: 9010
  swagger:
    server: http://localhost:9010
    auth:
      username: admin
      password: admin

log:
  format: pretty
  level: info

misc:
  cdnUrl: http://127.0.0.1:9000/homebase

guard:
  pending: 30
  limit: 5
  secretKey: mySecretKey
  refreshKey: myRefreshKey
  expired: 30 days
  skipOtp: true

mongo:
  host: localhost
  port: 27017
  username: homebase_user
  password: homebase_pass
  database: homebase_db
  connectTimeout: 20000
  directConnection: true
  debug: false

storage:
  region: ap-southeast-1
  accessKey: accesskey
  secretKey: secretkey
  bucket: homebase
  endpoint: http://127.0.0.1:9000
  useSSL: false
  s3ForcePathStyle: true
  linkFormat: http://127.0.0.1:9000/homebase/<key>
